[makejinja]
inputs = "./template/resume"
output = "./resume"
exclude_patterns = [".mjfilter.py"]
data = ["./resume.yaml"]
import_paths = ["./scripts"]
loaders = ["plugin:Plugin"]
jinja_suffix = ".j2"
force = true
undefined = "chainable"

[makejinja.delimiter]
block_start = "#%"
block_end = "%#"
comment_start = "#|"
comment_end = "#|"
variable_start = "#{"
variable_end = "}#"
